### ISSUE TITLE
Launch crash with Optifine

### ISSUE THREAD

**Issue by Madis0** [Siphalor/amecs#2]
- Minecraft 1.14.3
- OptiFine 1.14.3 HD U F1
- OptiFabric 0.3.1
- Fabric Loader 0.4.8 build.155 1.14.3

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 30.06.19 16:20
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_310.method_1503(class_310.java:441)
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method handler$onKeyBindingWritten$zzf000(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/io/PrintWriter;[Lnet/minecraft/class_304;IILnet/minecraft/class_304;)V in amecs.mixins.json:MixinGameOptions failed injection check, (0/1) succeeded. Using refmap amecs-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1203)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:939)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:323)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:179)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:142)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_310.method_1503(class_310.java:441)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:395)
	at net.minecraft.client.main.Main.main(Main.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.3
	Operating System: Linux (amd64) version 4.19.49-1-MANJARO
	Java Version: 1.8.0_212, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 926272976 bytes (883 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.4.8+build.155-1.14.3
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ MixinTransformerError: An unexpected critical error was encountered
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>
```

**Comment by Siphalor** [comment]
This issue should be supressed now (It doesn't crash but Amecs will have limited functionality)

**Comment by Madis0** [comment]
Seems to be fixed with the latest Amecs or at least I don't see anything limited about it.

**Comment by IdrisQe** [comment]
> Try updating Fabric loader and API.

Tried the latest Fabric Loader (I was only 1 version behind) and my API was already up-to-date.
Still not showing...

**Comment by IdrisQe** [comment]
Does "limited functionality" include the built-in auto-jump hotkey not being editable?
Because it's not appearing in my controls menu with Optifabric/Optifine and Amecs.
(Note that the sole reason I'm using Amecs is because I'm using Mouse Wheelie and it doesn't let you NOT use it. Why exactly is Amecs required for and embedded in MW?)

This is incredibly annoying, as it conflicts with the waypoint hotkey I'm using with Voxelmap. I'd MUCH prefer to keep the waypoint hotkey set to B, but given I can't edit Amecs' stupid built-in autojump which wasn't actually described as a feature anywhere, I'll probably have to edit it. Amusing that the mod which is supposed to make hotkeys work better is also the mod which is completely screwing up my hotkeys.

**Comment by Madis0** [comment]
I see the auto jump feature and also the skin layer keybinds for that matter. Using latest Optifine and Optifabric.

**Comment by Siphalor** [comment]
Hey guys, 

thanks for the thoughts about the mods.

Some notes:
1. I experimented a bit and it seems like Informed Load kills **all** keybindings added the standard way. (Voxel Map is closed source so I can only guess it does some non-standard stuff to register it's keybindings)
2. The "limited features" means that modifier keys (which are the main front-end feature) won't be able to be saved.
3. Mouse Wheelie uses Amecs because they was a high request to make a lot of Mouse Wheelie's key/button presses configurable. Amecs' API is designed to provide extended key bindings which require a lot of work otherwise.
4. The reason because MW embeds Amecs is that I like one-jar-mods. There's really nothing more than making it easier for users since they are not required to download another mod.
5. Consider don't yelling at modders ;) Most of us are doing this voluntary in their freetime and that's not a good motivation 😃 

Have a nice day

**Comment by magneticflux-** [comment]
Is this issue suppressed in the 1.15 branch? I'm encountering something similar:
```
Expected: [Ljava/io/PrintWriter;, [Lnet/minecraft/class_304;, I, I, Lnet/minecraft/class_304;]
   Found: [Ljava/io/PrintWriter;, Lnull;, [Lnet/minecraft/class_304;, I, I]
[14:38:50] [main/FATAL]: /********************************************************************************************************************************************************************/
[14:38:50] [main/FATAL]: /*                                                                          Invalid Mixin                                                                           */
[14:38:50] [main/FATAL]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[14:38:50] [main/FATAL]: /*     Action : APPLY                                                                                                                                               */
[14:38:50] [main/FATAL]: /*      Mixin : de.siphalor.amecs.mixin.MixinGameOptions                                                                                                            */
[14:38:50] [main/FATAL]: /*     Config : amecs.mixins.json                                                                                                                                   */
[14:38:50] [main/FATAL]: /*      Phase : DEFAULT                                                                                                                                             */
[14:38:50] [main/FATAL]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[14:38:50] [main/FATAL]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException                                                                                   */
[14:38:50] [main/FATAL]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[14:38:50] [main/FATAL]: /*     Injection validation failed: Callback method                                                                                                                 */
[14:38:50] [main/FATAL]: /*     onKeyBindingWritten(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/io/PrintWriter;[Lnet/minecraft/class_304;IILnet/minecraft/class_304;) */
[14:38:50] [main/FATAL]: /*      in amecs.mixins.json:MixinGameOptions expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap amecs-refmap.json [INJECT Applicator      */
[14:38:50] [main/FATAL]: /*     Phase -> amecs.mixins.json:MixinGameOptions -> Apply Injections ->  -> PostInject ->                                                                         */
[14:38:50] [main/FATAL]: /*     amecs.mixins.json:MixinGameOptions->@Inject::onKeyBindingWritten(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/io/PrintWriter;[Lnet/min */
[14:38:50] [main/FATAL]: /*     craft/class_304;IILnet/minecraft/class_304;)V]                                                                                                               */
[14:38:50] [main/FATAL]: /*------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
[14:38:50] [main/FATAL]: /*     org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Injection validation failed: Callback method                                     */
[14:38:50] [main/FATAL]: /*     onKeyBindingWritten(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/io/PrintWriter;[Lnet/minecraft/class_304;IILnet/minecraft/class_304;) */
[14:38:50] [main/FATAL]: /*      in amecs.mixins.json:MixinGameOptions expected 1 invocation(s) but 0 succeeded. Scanned 1 target(s). Using refmap amecs-refmap.json [INJECT Applicator      */
[14:38:50] [main/FATAL]: /*     Phase -> amecs.mixins.json:MixinGameOptions -> Apply Injections ->  -> PostInject ->                                                                         */
[14:38:50] [main/FATAL]: /*     amecs.mixins.json:MixinGameOptions->@Inject::onKeyBindingWritten(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/io/PrintWriter;[Lnet/min */
[14:38:50] [main/FATAL]: /*     craft/class_304;IILnet/minecraft/class_304;)V]                                                                                                               */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:395)                                                            */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)                                                 */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)                                       */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)                                             */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)                                                  */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)                                                      */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)                                                              */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)                                                              */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)                                                       */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)                                                  */
[14:38:50] [main/FATAL]: /*         org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)                             */
[14:38:50] [main/FATAL]: /*         net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:174)                                                              */
[14:38:50] [main/FATAL]: /*         net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)                                                                      */
[14:38:50] [main/FATAL]: /*         java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)                                                                                          */
[14:38:50] [main/FATAL]: /*         java.base/java.lang.Class.getDeclaredFields0(Native Method)                                                                                              */
[14:38:50] [main/FATAL]: /*         java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3066)                                                                                      */
[14:38:50] [main/FATAL]: /*         java.base/java.lang.Class.getDeclaredFields(Class.java:2253)                                                                                             */
[14:38:50] [main/FATAL]: /*         net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)                                                                                 */
[14:38:50] [main/FATAL]: /*         net.optifine.reflect.Reflector.<clinit>(Reflector.java:508)                                                                                              */
[14:38:50] [main/FATAL]: /*         net.minecraft.class_128.method_559(class_128.java:101)                                                                                                   */
[14:38:50] [main/FATAL]: /*         net.minecraft.class_128.<init>(class_128.java:54)                                                                                                        */
[14:38:50] [main/FATAL]: /*         net.minecraft.class_128.method_24305(class_128.java:414)                                                                                                 */
[14:38:50] [main/FATAL]: /*         net.minecraft.client.main.Main.main(Main.java:129)                                                                                                       */
[14:38:50] [main/FATAL]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                           */
[14:38:50] [main/FATAL]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                         */
[14:38:50] [main/FATAL]: /*         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                 */
[14:38:50] [main/FATAL]: /*         java.base/java.lang.reflect.Method.invoke(Method.java:567)                                                                                               */
[14:38:50] [main/FATAL]: /*         net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)                                                                    */
[14:38:50] [main/FATAL]: /*         net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)                                                                                                 */
[14:38:50] [main/FATAL]: /*         net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)                                                                                      */
[14:38:50] [main/FATAL]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                           */
[14:38:50] [main/FATAL]: /*         java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                         */
[14:38:50] [main/FATAL]: /*         java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                                 */
[14:38:50] [main/FATAL]: /*         java.base/java.lang.reflect.Method.invoke(Method.java:567)                                                                                               */
[14:38:50] [main/FATAL]: /*         org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)                                                                           */
[14:38:50] [main/FATAL]: /*         org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)                                                                                        */
[14:38:50] [main/FATAL]: /*         org.multimc.EntryPoint.listen(EntryPoint.java:143)                                                                                                       */
[14:38:50] [main/FATAL]: /*         org.multimc.EntryPoint.main(EntryPoint.java:34)                                                                                                          */
[14:38:50] [main/FATAL]: /********************************************************************************************************************************************************************/
```

Mods used: 
- `amecs-1.2.9+1.15-pre5`
- `mousewheelie-1.4.0+1.15.2-pre1`
- `optifabric-1.0.0-beta1`
- `preview_OptiFine_1.15.2_HD_U_G1_pre1`

**Comment by magneticflux-** [comment]
My issue was solved after updating to OptiFabric `1.0.0-beta3` ***AND*** deleting the `.optifine` folder in my `.minecraft` directory. OptiFabric doesn't redo the installation process unless the OptiFine version changes, so the fix in `beta3` wasn't applied at first.
