### ISSUE TITLE
Support for Controlling

### ISSUE THREAD

**Issue by Lukebb04** [Siphalor/amecs#49]
Add support for the [Controlling](https://www.curseforge.com/minecraft/mc-mods/controlling)

**Comment by Klotzi111** [comment]
You imply that it is incompatible. But did you try it? If so can you please send the game's `latest.log`. Because without any clue why it does not work I can not really help

**Comment by Lukebb04** [comment]
if you hold control (or and of those keys) it just selects it

**Comment by Klotzi111** [comment]
Okay good to know. But the version of Amecs and the version of Controlling you are using would help

**Comment by Klotzi111** [comment]
Okay. I found the problem and I know how to fix it. But it will take a while, because I am currently busy with other duty

**Comment by Klotzi111** [comment]
If you need to set the modifiers for a key until i fixed the mod: You can edit the `options.amecsapi.txt` file. Search for the key you want to set the modifiers and change the comma seperated values after the `:`.
Example: ```key_modifiers_key.drop:0,0,0```
These values represent the following modifier key in that order:
``ALT,CONTROL,SHIFT``
`0` means: modifier not required
`1` means: modifier required

**Comment by Boobies** [comment]
Note that I have mentioned a workaround in that bug report over there.

**Comment by Klotzi111** [comment]
> Note that I have mentioned a workaround in that bug report over there.

Yea, your workaround works. But the problem is not the mod load order. And I think it is not good when Controlling also tries to add key modifiers. This will cause more problems. I need to fix it in Amecs. And as I mentioned I will fix it.

**Comment by Boobies** [comment]
It would not cause more problems because there would be no need to use both mods simultaneously.

**Comment by Klotzi111** [comment]
A new version of Amecs is out. It now supports Controlling
You can download it here: https://github.com/Klotzi111/amecs/releases/tag/1.4.3

**Comment by Anoaxx** [comment]
cant wait for this made into real amecs

**Comment by Anoaxx** [comment]
> A new version of Amecs is out. It now supports Controlling You can download it here: https://github.com/Klotzi111/amecs/releases/tag/1.4.3

you gonna bump version of your fork cause this "made into real amecs" its takes long

**Comment by EGOIST1372** [comment]
@Klotzi111 Hi after I used your amecs v1.4.3 the game crashes on startup

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/11/22
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_312 failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:492)
	at net.minecraft.client.main.Main.main(Main:197)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at de.klotzi111.transformerinterceptor.api.basic.transformer.AbstractMixinTransformerProxy.transformClassBytes(AbstractMixinTransformerProxy.java:38)
	at de.klotzi111.transformerinterceptor.impl.event.basic.EventGeneratorMixinTransformerProxy.transform(EventGeneratorMixinTransformerProxy.java:39)
	at de.klotzi111.transformerinterceptor.api.basic.BasicTransformerInterceptor.transformClass(BasicTransformerInterceptor.java:26)
	at de.klotzi111.transformerinterceptor.impl.event.basic.EventGeneratorMixinTransformerProxy.transformClassBytes(EventGeneratorMixinTransformerProxy.java:53)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_312::method_1598(JDD)V has incompatible changes at opcode 162 in callback amecsapi.mixins.json:MixinMouse->@Inject::isSpectator_onMouseScroll(JDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;DF)V from mod amecsapi.
 Expected: [D, F]
    Found: [D, I]
Available: [D, I]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 19 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.<init>(class_310.java:492)

**Comment by Klotzi111** [comment]
@EGOIST1372 Please send me your `latest.log` log file after the crash happend. This file contains all the information I need to find the problem. Currently I can not reproduce this error.

**Comment by EGOIST1372** [comment]
@Klotzi111 here you go
[latest.log](https://github.com/Siphalor/amecs/files/8693233/latest.log)

**Comment by Anoaxx** [comment]
interesting... 

[19:44:43] [main/WARN]: Warnings were found!
 - Mod 'CIT Resewn: Defaults' (citresewn-defaults) 1.0.1+1.18.2 conflicts with any version of mod 'Eating Animation' (eatinganimationid), which is present with the following versions: 1.6!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'CIT Resewn: Defaults' (citresewn-defaults) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
 - Mod 'DeathLog' (deathlog) 0.2.7+1.18 recommends version 3.1.0 or later of trinkets, which is missing!
	 - You should install version 3.1.0 or later of trinkets for the optimal experience.
 - Mod 'Modget' (modget) 0.4.3+1.17 recommends any version of server_translations_api, which is missing!
	 - You should install any version of server_translations_api for the optimal experience.
 - Mod 'Modget Core' (modget-core) 0.4.3 recommends any version of server_translations_api, which is missing!
	 - You should install any version of server_translations_api for the optimal experience.

**Comment by Anoaxx** [comment]
[19:45:11] [Render thread/ERROR]: Critical injection failure: LVT in net/minecraft/class_312::method_1598(JDD)V has incompatible changes at opcode 162 in callback amecsapi.mixins.json:MixinMouse->@Inject::isSpectator_onMouseScroll(JDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;DF)V from mod amecsapi.
 Expected: [D, F]
    Found: [D, I]
Available: [D, I]

This is everyghing about amecs in this log. btw its the same lines from crashlog.

As far as i can tell... You trying play 1.18.2 and @Klotzi111 version don't support 1.18.2

**Comment by Klotzi111** [comment]
Yea that is correct. This version of my amecs does not support mc 1.18.2.
The `latest.log` tells the used mc version in the first line.
But the crash log sent before did not really tell the mc version. Only for a mod it was saing `at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)` which let me assume mc 1.18.1. And I tried to reproduce the error but it worked for me with 1.18.1.

I remember me already fixing that 1.18.2 incompatibility. I try to release a 1.18.2 compatible version soon.

**Comment by Anoaxx** [comment]
> I remember me already fixing that 1.18.2 incompatibility. I try to release a 1.18.2 compatible version soon.

can't wait *-*

**Comment by Klotzi111** [comment]
I released a new version 1.4.4 that works with mc 1.18.2.
You can find it on the releases page of my repo.

**Comment by Anoaxx** [comment]
> I released a new version 1.4.4 that works with mc 1.18.2. You can find it on the releases page of my repo.

why your version cant go to official into amecs or seperate mod

**Comment by EGOIST1372** [comment]
@Klotzi111 Thanks for update
Also can you update NMUK to 1.18.2 as well?

**Comment by Klotzi111** [comment]
> why your version cant go to official into amecs

The original mod author knows about my fork. And some (old) pull requests of me are still pending. I could remind him about my fork by opening a new pull request. But in the end it is up to Siphalor (the author) to look into my fork and take over the changes. So maybe you ask him.


> ... or seperate mod

I definitely could but I do not feel that well about "stealing" the original source by releasing it as a new mod. I would prefer my changes to be in the original.

**Comment by Klotzi111** [comment]
> Also can you update NMUK to 1.18.2 as well?

(That is definitely not the right issue for that but it is too late now :D )
I will look into it.
Edit: My NMUK version 1.3.0 already works for mc 1.18.2

**Comment by EGOIST1372** [comment]
@Klotzi111 let me ask to be sure, your fork only solved controlling support or it has other changes and improvements as well?
also can you update AMECS and NMUK to 1.19 ?! :D
thanks <3

**Comment by Klotzi111** [comment]
@EGOIST1372 My fork has additional features and many bug fixes:

- Many fixes in the controls GUI where you add and remove alternative Keybindings. Especially when there is a filter/search active via Amecs or Controlling.
- Fixed a bug where the keybinding sometimes was not triggered with alternative keys.
- Made it more intuitive to remove alternative keys: Assigning "no key" will remove the alternative.
- Improved the internal API a lot. Especially in `NMUKKeyBindingHelper`.

I am currently working on 1.19 support for my forks. I think I will finish them the next days.

**Comment by EGOIST1372** [comment]
@Klotzi111 can't you just make a pr for each fix and feature so all can get into the official build?
and why dev not implemented them?

**Comment by Klotzi111** [comment]
Tearing apart the repo for every feature/fix is quite laborious and also not really good. Because I overhauled the internal api. So I would need to include the changes for that internal api in every fix which then would make merging more than one pr more difficult.

> and why dev not implemented them?

I do not know. Probably because I made so many changes.
He could just take over my code if he wants.

**Comment by Klotzi111** [comment]
@EGOIST1372 I just wanted to inform you. My forks are now updated and released.

**Comment by EGOIST1372** [comment]
@Klotzi111 thanks so much <3
but why the file size is 900+KB?

**Comment by TalEdd** [comment]
@Klotzi111 
Hi, I seem to be crashing with your forked Amecs v1.4.5 on MC 1.19. [latest.log](https://github.com/Siphalor/amecs/files/9437853/latest.log)
Your forked NMUK v1.3.1 is working perfectly fine though.🤔

**Comment by Klotzi111** [comment]
@TalEdd My Amecs fork crashes because it is incompatible with the mod `interactic`. I already know that. But a fix is not trivial.
You can remove either `interactic` or `amecs` to make your game run.

**Comment by TalEdd** [comment]
@Klotzi111
Oh, I didn't realise. I will remove Interactic then, Amecs is too good to pass up on. I'll try another mod called Item Physics(maybe it's compatible?).

If you don't mind, could you put a list of incompatible mods on your forked github Readme page?

**Comment by Klotzi111** [comment]
@TalEdd Just another option I should have listed in the last post: You can replace `amecs` with its dependency [amecs-api](https://github.com/Klotzi111/amecs-api) if your main goal is to get the keybinding modifier keys. You will only lose the additional keybindings that `amecs` adds.

> I'll try another mod called Item Physics(maybe it's compatible?).

I do not know whether that mod is compatible or not. Just try it. (And optionally create an issue if it is not)

> If you don't mind, could you put a list of incompatible mods on your forked github Readme page?

Yea. I good idea. I just did that

**Comment by netcore10** [comment]
controlling still breaks amecs for 1.19.2 for some reason.

**Comment by Anoaxx** [comment]
> controlling still breaks amecs for 1.19.2 for some reason.

but you downloads klotzi's fork or siphalor's version?

**Comment by netcore10** [comment]
> > controlling still breaks amecs for 1.19.2 for some reason.
> 
> but you downloads klotzi's fork or siphalor's version?

Siphalor's

**Comment by Klotzi111** [comment]
@netcore10 Currently Siphalor's is not compatible with Controlling. You can use [my forked version](https://github.com/Klotzi111/amecs/releases). It is compatible.

**Comment by netcore10** [comment]
> @netcore10 Currently Siphalor's is not compatible with Controlling. You can use [my forked version](https://github.com/Klotzi111/amecs/releases). It is compatible.

@Klotzi111 Your version crashes on 1.19.2, should i add an issue?

**Comment by Klotzi111** [comment]
@netcore10 Sure on my fork repo. I can only fix it if I know about it. 😄

**Comment by EGOIST1372** [comment]
@Klotzi111 Can't you just make a pr for each fix and feature so all can get
into the official build?
And why dev not implemented them?

**Comment by Klotzi111** [comment]
@EGOIST1372 See https://github.com/Siphalor/amecs/issues/49#issuecomment-1172343823

**Comment by EGOIST1372** [comment]
@Klotzi111 I installed your AMEC and NUMK and AMEC-api and it seems it crashes in 1.19.3
can you update it to 1.19.3?
thanks in advance <3

crash log:
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'advanced_runtime_resource_pack'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'advanced_runtime_resource_pack'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.devtech.arrp.ARRP failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 5 more
Caused by: java.lang.ExceptionInInitializerError
	at de.klotzi111.fabricmultiversionhelper.impl.FabricMultiVersionHelper.<clinit>(FabricMultiVersionHelper.java:19)
	at de.klotzi111.fabricmultiversionhelper.api.mixinselect.MixinSelectConfig.loadMixinSelectConfig(MixinSelectConfig.java:89)
	at de.klotzi111.fabricmultiversionhelper.api.mixinselect.MixinSelectConfig.loadMixinSelectConfig(MixinSelectConfig.java:82)
	at de.klotzi111.fabricmultiversionhelper.api.mixinselect.MixinSelectConfig.loadMixinSelectConfig(MixinSelectConfig.java:76)
	at de.siphalor.amecs.mixin.AmecsMixinConfig.onLoad(AmecsMixinConfig.java:29)
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: java.lang.RuntimeException: Failed to load all required reflective accessors
	at de.klotzi111.util.GsonUtil.GsonUtil.<clinit>(GsonUtil.java:55)
	... 28 more
Caused by: java.lang.NoSuchMethodException: com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(com.google.gson.Gson,com.google.gson.reflect.TypeToken,java.lang.Class)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
	at de.klotzi111.util.GsonUtil.GsonUtil.<clinit>(GsonUtil.java:48)
	... 28 more

**Comment by EGOIST1372** [comment]
@Siphalor Hi
can you please take over @Klotzi111 code and make amecs compatible with controlling ?
he offered you to take over his code in [here](https://github.com/Siphalor/amecs/issues/49#issuecomment-1172343823)
it's true that he changed a lot of stuff but he says he can't make all of them into prs since its so hard to do so
you can take over and change stuff that you don't like about it, meantime users can enjoy those fixes and compatibilities benefits

**Comment by Siphalor** [comment]
Hi everyone,

I'm just gonna explain the status of this issue and Klotzi's PR:

When Klotzi opened his PR‌, we had a talk about the changes.
While his PR addresses a lot of issues, it also contains a couple of structural changes to the source code that I disagree with.
This subjective changes are interwoven with changes and fixes I actually approve of, making it nearly impossible to separate them.
One of his biggest changes is having a single jar supporting all Minecraft versions.
In my opinion, this increases the maintenance burden, and it generally doesn't fit my release model.

I took a few attempts of separating the changes made in the PR but ultimately failed.
The changes will probably have to be developed separately from the ground up again.

I currently don't have a lot of time and energy for modding and have a lot of projects, so I can't give an ETA for any issues or suggestions.

---

Since this thread is getting bumped regularly without any new information on the actual issue, I'm gonna lock this issue now.
If you want to report issues with Klotzi's PR, please directly comment on the PR (#44).

**Comment by Siphalor** [comment]
Suport for Controlling has been added in Amecs in version 1.7.
