### ISSUE TITLE
Crash after trying to change menu keybind

### ISSUE THREAD

**Issue by carterprince** [Siphalor/amecs#68]
Crash occurs shortly after clicking the button to change the keybind.
Mod version: 1.19.3
Game version: 1.19.4

Crash log:

```
java.lang.AbstractMethodError: Receiver class de.siphalor.amecs.gui.SearchFieldControlsListWidget does not define or inherit an implementation of the resolved method 'abstract void method_48269()' of abstract class net.minecraft.class_459$class_461.
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_459.method_49007(class_459.java:61)
	at net.minecraft.class_459.method_49006(class_459.java:57)
	at net.minecraft.class_459$class_462.method_19871(class_459.java:127)
	at net.minecraft.class_4185.method_25306(class_4185.java:94)
	at net.minecraft.class_4264.method_25348(class_4264.java:57)
	at net.minecraft.class_339.method_25402(class_339.java:187)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_4265$class_4266.method_25402(class_4265.java:135)
	at net.minecraft.class_350.method_25402(class_350.java:328)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_6599.method_25402(class_6599.java:49)
	at net.minecraft.class_312.method_1611(class_312.java:98)
	at net.minecraft.class_437.method_25412(class_437.java:540)
	at net.minecraft.class_312.method_1601(class_312.java:98)
	at net.minecraft.class_312.method_22686(class_312.java:169)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:169)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:198)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:209)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1238)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

I looked more into `method_48269`, and it appears to refer to a method called `update`. It's likely this was changed from 1.19.3 to 1.19.4, so that's probably the cause.

**Comment by carterprince** [comment]
Probably duplicate of https://github.com/Siphalor/amecs/issues/61
